//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Energistics.DataAccess.PRODML122;
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://www.prodml.org/api/210/genericDataAccess", ClrNamespace="www.prodml.org.api._210.genericDataAccess")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess", ConfigurationName="PROD_GenericDataAccessSoap")]

public interface PROD_GenericDataAccessSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.prodml.org/api/210/genericDataAccess/GetCapabilities", ReplyAction="http://www.prodml.org/api/210/genericDataAccess/GetCapabilitiesResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="getCapabilitiesResult")]
    GenericDataAccessCapabilities GetCapabilities();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.prodml.org/api/210/genericDataAccess/GetData", ReplyAction="http://www.prodml.org/api/210/genericDataAccess/GetDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnsupportedOptionFault), Action="http://www.prodml.org/api/210/genericDataAccess/GetData", Name="UnsupportedOptionFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnsupportedDataObjectFault), Action="http://www.prodml.org/api/210/genericDataAccess/GetData", Name="UnsupportedDataObjectFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnknownUidFault), Action="http://www.prodml.org/api/210/genericDataAccess/GetData", Name="UnknownUidFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.InvalidXPathFault), Action="http://www.prodml.org/api/210/genericDataAccess/GetData", Name="InvalidXPathFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnsupportedCriterionFault), Action="http://www.prodml.org/api/210/genericDataAccess/GetData", Name="UnsupportedCriterionFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.MissingParameterFault), Action="http://www.prodml.org/api/210/genericDataAccess/GetData", Name="MissingParameterFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="getDataResult")]
    GetDataResult GetData(GetDataQuery query);
    
    // CODEGEN: Parameter 'putDataResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.prodml.org/api/210/genericDataAccess/PutData", ReplyAction="http://www.prodml.org/api/210/genericDataAccess/PutDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnsupportedOptionFault), Action="http://www.prodml.org/api/210/genericDataAccess/PutData", Name="UnsupportedOptionFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnsupportedDataObjectFault), Action="http://www.prodml.org/api/210/genericDataAccess/PutData", Name="UnsupportedDataObjectFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnknownUidFault), Action="http://www.prodml.org/api/210/genericDataAccess/PutData", Name="UnknownUidFault")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.MissingParameterFault), Action="http://www.prodml.org/api/210/genericDataAccess/PutData", Name="MissingParameterFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="putDataResult")]
    PutDataResponse PutData(PutDataRequest request);
    
    // CODEGEN: Parameter 'Uid' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="http://www.prodml.org/api/210/genericDataAccess/DeleteData", ReplyAction="http://www.prodml.org/api/210/genericDataAccess/DeleteDataResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(www.prodml.org.api._210.genericDataAccess.UnknownUidFault), Action="http://www.prodml.org/api/210/genericDataAccess/DeleteData", Name="UnknownUidFault")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="deleteDataResult")]
    DeleteDataResponse DeleteData(DeleteDataRequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class GenericDataAccessCapabilities
{
    
    private SupportedDataObject[] supportedDataObjectsField;
    
    private NameValuePair[] propertiesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public SupportedDataObject[] SupportedDataObjects
    {
        get
        {
            return this.supportedDataObjectsField;
        }
        set
        {
            this.supportedDataObjectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public NameValuePair[] Properties
    {
        get
        {
            return this.propertiesField;
        }
        set
        {
            this.propertiesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class SupportedDataObject
{
    
    private string nameField;
    
    private SupportedOperation[] supportedOperationField;
    
    private string versionField;
    
    private string namespaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupportedOperation", Order=1)]
    public SupportedOperation[] SupportedOperation
    {
        get
        {
            return this.supportedOperationField;
        }
        set
        {
            this.supportedOperationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @namespace
    {
        get
        {
            return this.namespaceField;
        }
        set
        {
            this.namespaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public enum SupportedOperation
{
    
    /// <remarks/>
    GetData,
    
    /// <remarks/>
    PutData,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class DeleteDataResult
{
    
    private int countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int Count
    {
        get
        {
            return this.countField;
        }
        set
        {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class PutDataResult
{
    
    private PutDataResultStatus statusField;
    
    private string idField;
    
    private string suppMsgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public PutDataResultStatus Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SuppMsg
    {
        get
        {
            return this.suppMsgField;
        }
        set
        {
            this.suppMsgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public enum PutDataResultStatus
{
    
    /// <remarks/>
    Added,
    
    /// <remarks/>
    Updated,
}
 

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class GetDataResult
{
    
    private AbstractObject abstractDataObjectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.energistics.org/schemas/abstract", Order=0)]
    public AbstractObject abstractDataObject
    {
        get
        {
            return this.abstractDataObjectField;
        }
        set
        {
            this.abstractDataObjectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class GroupingIntervalType
{
    
    private string uomField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string uom
    {
        get
        {
            return this.uomField;
        }
        set
        {
            this.uomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class GetDataSubsetOptions
{
    
    private SubsetTypes subsetTypeField;
    
    private bool subsetTypeFieldSpecified;
    
    private string maxValuesField;
    
    private GroupingFunctions groupingFunctionField;
    
    private bool groupingFunctionFieldSpecified;
    
    private GroupingIntervalType groupingIntervalField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public SubsetTypes SubsetType
    {
        get
        {
            return this.subsetTypeField;
        }
        set
        {
            this.subsetTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SubsetTypeSpecified
    {
        get
        {
            return this.subsetTypeFieldSpecified;
        }
        set
        {
            this.subsetTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
    public string MaxValues
    {
        get
        {
            return this.maxValuesField;
        }
        set
        {
            this.maxValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public GroupingFunctions GroupingFunction
    {
        get
        {
            return this.groupingFunctionField;
        }
        set
        {
            this.groupingFunctionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GroupingFunctionSpecified
    {
        get
        {
            return this.groupingFunctionFieldSpecified;
        }
        set
        {
            this.groupingFunctionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public GroupingIntervalType GroupingInterval
    {
        get
        {
            return this.groupingIntervalField;
        }
        set
        {
            this.groupingIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public enum SubsetTypes
{
    
    /// <remarks/>
    UidOnly,
    
    /// <remarks/>
    HeaderOnly,
    
    /// <remarks/>
    Range,
    
    /// <remarks/>
    Aggregate,
    
    /// <remarks/>
    Interpolate,
    
    /// <remarks/>
    Current,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public enum GroupingFunctions
{
    
    /// <remarks/>
    Average,
    
    /// <remarks/>
    Minimum,
    
    /// <remarks/>
    Maximum,
    
    /// <remarks/>
    Sum,
    
    /// <remarks/>
    Raw,
    
    /// <remarks/>
    StdDeviation,
    
    /// <remarks/>
    Any,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class GetDataOptions
{
    
    private string requestedUomField;
    
    private GetDataSubsetOptions subsetOptionsField;
    
    private NameValuePair[] customOptionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string RequestedUom
    {
        get
        {
            return this.requestedUomField;
        }
        set
        {
            this.requestedUomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public GetDataSubsetOptions SubsetOptions
    {
        get
        {
            return this.subsetOptionsField;
        }
        set
        {
            this.subsetOptionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public NameValuePair[] CustomOptions
    {
        get
        {
            return this.customOptionsField;
        }
        set
        {
            this.customOptionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class NameValuePair
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class SelectionCriterion
{
    
    private string pathField;
    
    private SelectionCriterionOperator operatorField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public SelectionCriterionOperator Operator
    {
        get
        {
            return this.operatorField;
        }
        set
        {
            this.operatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public enum SelectionCriterionOperator
{
    
    /// <remarks/>
    lt,
    
    /// <remarks/>
    le,
    
    /// <remarks/>
    eq,
    
    /// <remarks/>
    gt,
    
    /// <remarks/>
    ge,
    
    /// <remarks/>
    ne,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class EndpointQualifiedDepth
{
    
    private EndpointQualifier endpointField;
    
    private bool endpointFieldSpecified;
    
    private double valueField;
    
    public EndpointQualifiedDepth()
    {
        this.endpointField = EndpointQualifier.Inclusive;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public EndpointQualifier endpoint
    {
        get
        {
            return this.endpointField;
        }
        set
        {
            this.endpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endpointSpecified
    {
        get
        {
            return this.endpointFieldSpecified;
        }
        set
        {
            this.endpointFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public enum EndpointQualifier
{
    
    /// <remarks/>
    Inclusive,
    
    /// <remarks/>
    Exclusive,
    
    /// <remarks/>
    Extensive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class DepthRange
{
    
    private string pathField;
    
    private string uomField;
    
    private EndpointQualifiedDepth fromValueField;
    
    private EndpointQualifiedDepth toValueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Uom
    {
        get
        {
            return this.uomField;
        }
        set
        {
            this.uomField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public EndpointQualifiedDepth FromValue
    {
        get
        {
            return this.fromValueField;
        }
        set
        {
            this.fromValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public EndpointQualifiedDepth ToValue
    {
        get
        {
            return this.toValueField;
        }
        set
        {
            this.toValueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class EndpointQualifiedDateTime
{
    
    private EndpointQualifier endpointField;
    
    private System.DateTime valueField;
    
    public EndpointQualifiedDateTime()
    {
        this.endpointField = EndpointQualifier.Inclusive;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(EndpointQualifier.Inclusive)]
    public EndpointQualifier Endpoint
    {
        get
        {
            return this.endpointField;
        }
        set
        {
            this.endpointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public System.DateTime Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class DateTimeRange
{
    
    private string pathField;
    
    private EndpointQualifiedDateTime t0Field;
    
    private EndpointQualifiedDateTime t1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public EndpointQualifiedDateTime T0
    {
        get
        {
            return this.t0Field;
        }
        set
        {
            this.t0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public EndpointQualifiedDateTime T1
    {
        get
        {
            return this.t1Field;
        }
        set
        {
            this.t1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class DataObjectReference
{
    
    private string versionField;
    
    private string namespaceField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @namespace
    {
        get
        {
            return this.namespaceField;
        }
        set
        {
            this.namespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess")]
public partial class GetDataQuery
{
    
    private DataObjectReference dataObjectField;
    
    private string[] uidField;
    
    private DateTimeRange dateTimeCriterionField;
    
    private DepthRange depthCriterionField;
    
    private string contentFilterField;
    
    private SelectionCriterion[] selectionCriteriaField;
    
    private GetDataOptions optionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public DataObjectReference DataObject
    {
        get
        {
            return this.dataObjectField;
        }
        set
        {
            this.dataObjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Uid", Order=1)]
    public string[] Uid
    {
        get
        {
            return this.uidField;
        }
        set
        {
            this.uidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DateTimeRange DateTimeCriterion
    {
        get
        {
            return this.dateTimeCriterionField;
        }
        set
        {
            this.dateTimeCriterionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public DepthRange DepthCriterion
    {
        get
        {
            return this.depthCriterionField;
        }
        set
        {
            this.depthCriterionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string ContentFilter
    {
        get
        {
            return this.contentFilterField;
        }
        set
        {
            this.contentFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SelectionCriteria", Order=5)]
    public SelectionCriterion[] SelectionCriteria
    {
        get
        {
            return this.selectionCriteriaField;
        }
        set
        {
            this.selectionCriteriaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public GetDataOptions Options
    {
        get
        {
            return this.optionsField;
        }
        set
        {
            this.optionsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PutData", WrapperNamespace="http://www.prodml.org/api/210/genericDataAccess", IsWrapped=true)]
public partial class PutDataRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.energistics.org/schemas/abstract", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.energistics.org/schemas/abstract")]
    public AbstractObject abstractDataObject;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("options")]
    public NameValuePair[] options;
    
    public PutDataRequest()
    {
    }
    
    public PutDataRequest(AbstractObject abstractDataObject, NameValuePair[] options)
    {
        this.abstractDataObject = abstractDataObject;
        this.options = options;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PutDataResponse", WrapperNamespace="http://www.prodml.org/api/210/genericDataAccess", IsWrapped=true)]
public partial class PutDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("putDataResult")]
    public PutDataResult[] putDataResult;
    
    public PutDataResponse()
    {
    }
    
    public PutDataResponse(PutDataResult[] putDataResult)
    {
        this.putDataResult = putDataResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteData", WrapperNamespace="http://www.prodml.org/api/210/genericDataAccess", IsWrapped=true)]
public partial class DeleteDataRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("Uid")]
    public string[] Uid;
    
    public DeleteDataRequest()
    {
    }
    
    public DeleteDataRequest(string[] Uid)
    {
        this.Uid = Uid;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataResponse", WrapperNamespace="http://www.prodml.org/api/210/genericDataAccess", IsWrapped=true)]
public partial class DeleteDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.prodml.org/api/210/genericDataAccess", Order=0)]
    public DeleteDataResult deleteDataResult;
    
    public DeleteDataResponse()
    {
    }
    
    public DeleteDataResponse(DeleteDataResult deleteDataResult)
    {
        this.deleteDataResult = deleteDataResult;
    }
}
namespace www.prodml.org.api._210.genericDataAccess
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsupportedOptionFault", Namespace="http://www.prodml.org/api/210/genericDataAccess")]
    public partial class UnsupportedOptionFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OptionNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string OptionName
        {
            get
            {
                return this.OptionNameField;
            }
            set
            {
                this.OptionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsupportedDataObjectFault", Namespace="http://www.prodml.org/api/210/genericDataAccess")]
    public partial class UnsupportedDataObjectFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DataObjectNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string DataObjectName
        {
            get
            {
                return this.DataObjectNameField;
            }
            set
            {
                this.DataObjectNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnknownUidFault", Namespace="http://www.prodml.org/api/210/genericDataAccess")]
    public partial class UnknownUidFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UidField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Uid
        {
            get
            {
                return this.UidField;
            }
            set
            {
                this.UidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvalidXPathFault", Namespace="http://www.prodml.org/api/210/genericDataAccess")]
    public partial class InvalidXPathFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string XPathField;
        
        private string XPathProcessorErrorField;
        
        private long PositionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string XPath
        {
            get
            {
                return this.XPathField;
            }
            set
            {
                this.XPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string XPathProcessorError
        {
            get
            {
                return this.XPathProcessorErrorField;
            }
            set
            {
                this.XPathProcessorErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long Position
        {
            get
            {
                return this.PositionField;
            }
            set
            {
                this.PositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnsupportedCriterionFault", Namespace="http://www.prodml.org/api/210/genericDataAccess")]
    public partial class UnsupportedCriterionFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CriterionNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string CriterionName
        {
            get
            {
                return this.CriterionNameField;
            }
            set
            {
                this.CriterionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissingParameterFault", Namespace="http://www.prodml.org/api/210/genericDataAccess")]
    public partial class MissingParameterFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ParameterField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Parameter
        {
            get
            {
                return this.ParameterField;
            }
            set
            {
                this.ParameterField = value;
            }
        }
    }
}
