//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 
namespace Energistics.DataAccess.PRODML122.PROD_GenericDataProcessor {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PROD_GenericDataProcessorSoap", Namespace="http://www.prodml.org/api/210/genericDataProcessor")]
    public partial class PROD_GenericDataProcessor : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCapabilitiesOperationCompleted;
        
        /// <remarks/>
        public PROD_GenericDataProcessor() {
            this.Url = "http://_Vendor_Address_And_Port_/_Vendor_Service_Name_/";
        }
        
        /// <remarks/>
        public event ProcessDataCompletedEventHandler ProcessDataCompleted;
        
        /// <remarks/>
        public event GetCapabilitiesCompletedEventHandler GetCapabilitiesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prodml.org/api/210/genericDataProcessor/ProcessData", RequestNamespace="http://www.prodml.org/api/210/genericDataProcessor", ResponseNamespace="http://www.prodml.org/api/210/genericDataProcessor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("processDataResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProcessDataResult ProcessData([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string process, [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.energistics.org/schemas/abstract")] abstractObject abstractDataObject, [System.Xml.Serialization.XmlElementAttribute("options", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] NameValuePair[] options) {
            object[] results = this.Invoke("ProcessData", new object[] {
                        process,
                        abstractDataObject,
                        options});
            return ((ProcessDataResult)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProcessData(string process, abstractObject abstractDataObject, NameValuePair[] options, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProcessData", new object[] {
                        process,
                        abstractDataObject,
                        options}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProcessDataResult EndProcessData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProcessDataResult)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataAsync(string process, abstractObject abstractDataObject, NameValuePair[] options) {
            this.ProcessDataAsync(process, abstractDataObject, options, null);
        }
        
        /// <remarks/>
        public void ProcessDataAsync(string process, abstractObject abstractDataObject, NameValuePair[] options, object userState) {
            if ((this.ProcessDataOperationCompleted == null)) {
                this.ProcessDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataOperationCompleted);
            }
            this.InvokeAsync("ProcessData", new object[] {
                        process,
                        abstractDataObject,
                        options}, this.ProcessDataOperationCompleted, userState);
        }
        
        private void OnProcessDataOperationCompleted(object arg) {
            if ((this.ProcessDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataCompleted(this, new ProcessDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.prodml.org/api/210/genericDataProcessor/GetCapabilities", RequestNamespace="http://www.prodml.org/api/210/genericDataProcessor", ResponseNamespace="http://www.prodml.org/api/210/genericDataProcessor", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("getCapabilitiesResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GenericDataProcessorCapabilities GetCapabilities() {
            object[] results = this.Invoke("GetCapabilities", new object[0]);
            return ((GenericDataProcessorCapabilities)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCapabilities(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCapabilities", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public GenericDataProcessorCapabilities EndGetCapabilities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((GenericDataProcessorCapabilities)(results[0]));
        }
        
        /// <remarks/>
        public void GetCapabilitiesAsync() {
            this.GetCapabilitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetCapabilitiesAsync(object userState) {
            if ((this.GetCapabilitiesOperationCompleted == null)) {
                this.GetCapabilitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCapabilitiesOperationCompleted);
            }
            this.InvokeAsync("GetCapabilities", new object[0], this.GetCapabilitiesOperationCompleted, userState);
        }
        
        private void OnGetCapabilitiesOperationCompleted(object arg) {
            if ((this.GetCapabilitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCapabilitiesCompleted(this, new GetCapabilitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.energistics.org/schemas/abstract")]
    public abstract partial class abstractObject {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataProcessor")]
    public partial class DataObjectReference {
        
        private string versionField;
        
        private string namespaceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataProcessor")]
    public partial class GenericDataProcessorCapabilities {
        
        private DataObjectReference[] supportedDataObjectsField;
        
        private NameValuePair[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SupportedDataObject", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DataObjectReference[] SupportedDataObjects {
            get {
                return this.supportedDataObjectsField;
            }
            set {
                this.supportedDataObjectsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NameValuePair[] Properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataProcessor")]
    public partial class NameValuePair {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.prodml.org/api/210/genericDataProcessor")]
    public partial class ProcessDataResult {
        
        private abstractObject abstractDataObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.energistics.org/schemas/abstract")]
        public abstractObject abstractDataObject {
            get {
                return this.abstractDataObjectField;
            }
            set {
                this.abstractDataObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void ProcessDataCompletedEventHandler(object sender, ProcessDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProcessDataResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProcessDataResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void GetCapabilitiesCompletedEventHandler(object sender, GetCapabilitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCapabilitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCapabilitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GenericDataProcessorCapabilities Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GenericDataProcessorCapabilities)(this.results[0]));
            }
        }
    }
}
