//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PtaSync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PtaSync.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: true | false
        ///Description: The class type will be directly embedded within the complexType definition. Omit attribute or role type wrapper.
        /// </summary>
        internal static string XsdTagAnonymousRoleNote {
            get {
                return ResourceManager.GetString("XsdTagAnonymousRoleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: true | false
        ///Description: The class type will be anonymous for XML documents generated by the schema.
        /// </summary>
        internal static string XsdTagAnonymousTypeNote {
            get {
                return ResourceManager.GetString("XsdTagAnonymousTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As defined by XML Schema specification.
        /// </summary>
        internal static string XsdTagDefaultNote {
            get {
                return ResourceManager.GetString("XsdTagDefaultNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As defined by XML Schema specification.
        /// </summary>
        internal static string XsdTagFixedNote {
            get {
                return ResourceManager.GetString("XsdTagFixedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: qualified | unqualified
        ///Description: Overrides the elementFormDefault for this schema.
        /// </summary>
        internal static string XsdTagFormNote {
            get {
                return ResourceManager.GetString("XsdTagFormNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: As defined by XML Schema Datatypes specification.
        /// </summary>
        internal static string XsdTagMaxOccursNote {
            get {
                return ResourceManager.GetString("XsdTagMaxOccursNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: qualified | unqualified
        ///Description: Overrides the package-level default for naming complexType definitions.
        /// </summary>
        internal static string XsdTagMemberNamesNote {
            get {
                return ResourceManager.GetString("XsdTagMemberNamesNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: As defined by XML Schema Datatypes specification.
        /// </summary>
        internal static string XsdTagMinOccursNote {
            get {
                return ResourceManager.GetString("XsdTagMinOccursNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: true | false
        ///Default: false
        ///Description: Determines whether this element may contain mixed element and character content.  Refer to the W3C XML Schema recommendation.
        /// </summary>
        internal static string XsdTagMixedNote {
            get {
                return ResourceManager.GetString("XsdTagMixedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: all | sequence | choice
        ///Default: sequence
        ///Description: Overrides the package-level default model group.
        /// </summary>
        internal static string XsdTagModelGroupNote {
            get {
                return ResourceManager.GetString("XsdTagModelGroupNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values: true | false
        ///Description: As defined by XML Schema specification.
        /// </summary>
        internal static string XsdTagNillableNote {
            get {
                return ResourceManager.GetString("XsdTagNillableNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If assigned, indicates position in the sequence model group.
        /// </summary>
        internal static string XsdTagPositionNote {
            get {
                return ResourceManager.GetString("XsdTagPositionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anyURI
        ///base64Binary
        ///boolean
        ///byte
        ///date
        ///dateTime
        ///decimal
        ///double
        ///duration
        ///ENTITIES
        ///ENTITY
        ///float
        ///gDay
        ///gMonth
        ///gMonthDay
        ///gYear
        ///gYearMonth
        ///hexBinary
        ///ID
        ///IDREF
        ///IDREFS
        ///int
        ///integer
        ///language
        ///long
        ///Name
        ///NCName
        ///negativeInteger
        ///NMTOKEN
        ///NMTOKENS
        ///nonNegativeInteger
        ///nonPositiveInteger
        ///normalizedString
        ///NOTATION
        ///positiveInteger
        ///QName
        ///short
        ///string
        ///time
        ///token
        ///unsignedByte
        ///unsignedInt
        ///unsignedLong
        ///unsignedShort.
        /// </summary>
        internal static string XsdTypes {
            get {
                return ResourceManager.GetString("XsdTypes", resourceCulture);
            }
        }
    }
}
